OfferMaker.Web/Models/Account/AccountDetailsViewModel.cs
namespace OfferMaker.Web.Models.Account
{
    using OfferMaker.Services.Models.Account;

    public class AccountDetailsViewModel
    {
        public AccountDetailsServiceModel Account { get; set; }

        public bool UserIsAssignedAccountManager { get; set; }
    }
}

OfferMaker.Web/Controllers/AccountController.cs
namespace OfferMaker.Web.Controllers
{
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using OfferMaker.Data.Models;
    using OfferMaker.Web.Models.AccountViewModels;
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;

    [Authorize]
    [Route("[controller]/[action]")]
    public class AccountController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly ILogger _logger;

        public AccountController(
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            ILogger<AccountController> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [TempData]
        public string ErrorMessage { get; set; }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Login(string returnUrl = null)
        {
            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return RedirectToLocal(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToAction(nameof(LoginWith2fa), new { returnUrl, model.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToAction(nameof(Lockout));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> LoginWith2fa(bool rememberMe, string returnUrl = null)
        {
            // Ensure the user has gone through the username & password screen first
            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();

            if (user == null)
            {
                throw new ApplicationException($"Unable to load two-factor authentication user.");
            }

            var model = new LoginWith2faViewModel { RememberMe = rememberMe };
            ViewData["ReturnUrl"] = returnUrl;

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoginWith2fa(LoginWith2faViewModel model, bool rememberMe, string returnUrl = null)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var authenticatorCode = model.TwoFactorCode.Replace(" ", string.Empty).Replace("-", string.Empty);

            var result = await _signInManager.TwoFactorAuthenticatorSignInAsync(authenticatorCode, rememberMe, model.RememberMachine);

            if (result.Succeeded)
            {
                _logger.LogInformation("User with ID {UserId} logged in with 2fa.", user.Id);
                return RedirectToLocal(returnUrl);
            }
            else if (result.IsLockedOut)
            {
                _logger.LogWarning("User with ID {UserId} account locked out.", user.Id);
                return RedirectToAction(nameof(Lockout));
            }
            else
            {
                _logger.LogWarning("Invalid authenticator code entered for user with ID {UserId}.", user.Id);
                ModelState.AddModelError(string.Empty, "Invalid authenticator code.");
                return View();
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> LoginWithRecoveryCode(string returnUrl = null)
        {
            // Ensure the user has gone through the username & password screen first
            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null)
            {
                throw new ApplicationException($"Unable to load two-factor authentication user.");
            }

            ViewData["ReturnUrl"] = returnUrl;

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoginWithRecoveryCode(LoginWithRecoveryCodeViewModel model, string returnUrl = null)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null)
            {
                throw new ApplicationException($"Unable to load two-factor authentication user.");
            }

            var recoveryCode = model.RecoveryCode.Replace(" ", string.Empty);

            var result = await _signInManager.TwoFactorRecoveryCodeSignInAsync(recoveryCode);

            if (result.Succeeded)
            {
                _logger.LogInformation("User with ID {UserId} logged in with a recovery code.", user.Id);
                return RedirectToLocal(returnUrl);
            }
            if (result.IsLockedOut)
            {
                _logger.LogWarning("User with ID {UserId} account locked out.", user.Id);
                return RedirectToAction(nameof(Lockout));
            }
            else
            {
                _logger.LogWarning("Invalid recovery code entered for user with ID {UserId}", user.Id);
                ModelState.AddModelError(string.Empty, "Invalid recovery code entered.");
                return View();
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Lockout()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new User { UserName = model.Email, Email = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation("User created a new account with password.");
                    return RedirectToLocal(returnUrl);
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Action(nameof(ExternalLoginCallback), "Account", new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToAction(nameof(Login));
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToAction(nameof(Login));
            }

            // Sign in the user with this external login provider if the user already has a login.

OfferMaker.Web/Controllers/OpportunitiesController.cs
namespace OfferMaker.Web.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using OfferMaker.Data.Models;
    using OfferMaker.Services;
    using OfferMaker.Services.Models.Opportunity;
    using OfferMaker.Web.Infrastructure.Extensions;
    using OfferMaker.Web.Models.Opportunity;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class OpportunitiesController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IOpportunityService opportunities;
        private readonly IAccountService accounts;

        public OpportunitiesController(UserManager<User> userManager, IOpportunityService opportunities, IAccountService accounts)
        {
            this.userManager = userManager;
            this.opportunities = opportunities;
            this.accounts = accounts;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userId = this.userManager.GetUserId(User);

            return View(await this.opportunities.GetAllByUserIdAsync(userId));
        }

        [Authorize]
        public async Task<IActionResult> Create(int accountId)
        {
            if (!await this.ValidateUserIsAssignedAccountManager(accountId))
            {
                return Unauthorized();
            }

            var model = new OpportunityFormModel
            {
                AccountId = accountId,
                PotentialMembers = await GetUsersInOpportunityMemberRoleAsync()
            };

            return View(model);
        }

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        [HttpPost]
        public async Task<IActionResult> Create(OpportunityFormModel model)
        {
            if (!await this.ValidateUserIsAssignedAccountManager(model.AccountId))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                model.PotentialMembers = await GetUsersInOpportunityMemberRoleAsync();
                return View(model);
            }

            await this.opportunities.CreateAsync(
                model.Name,
                model.Description,
                model.AccountId,
                model.OportunityMembers
                );

            TempData.AddSuccessMessage($"Opportunity {model.Name} created successfully!");
            return RedirectToAction(controllerName: "Accounts", actionName: nameof(AccountsController.Details), routeValues: new { id = model.AccountId });
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var servicesModel = await this.opportunities.GetByIdAsync(id);
            var userIsMemberOfOpportunity = await this.ValidateUserIsMemberOfOpportunityAsync(id);

            if (servicesModel == null)
            {
                return NotFound();
            }

            var viewModel = new OpportunityDetailsViewModel
            {
                Opportunity = servicesModel,
                UserIsMemberOfOpportunity = userIsMemberOfOpportunity
            };

            return this.ViewOrNotFound(viewModel);
        }

        [Authorize(Roles = WebConstants.OpportunityMemberRole)]
        public async Task<IActionResult> Delete(int id)
        {
            if (!await this.ValidateUserIsMemberOfOpportunityAsync(id))
            {
                return Unauthorized();
            }

            var model = await this.opportunities.GetByIdAsync(id);

            return this.ViewOrNotFound(model);
        }

        [Authorize(Roles = WebConstants.OpportunityMemberRole)]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!await this.ValidateUserIsMemberOfOpportunityAsync(id))
            {
                return Unauthorized();
            }

            var model = await this.opportunities.GetByIdAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            var result = await this.opportunities.DeleteAsync(id);
            if (!result)
            {
                return NotFound();
            }

            TempData.AddSuccessMessage($"Opportunity {model.Name} deleted successfully!");
            return RedirectToAction("Details", "Accounts", new { id = model.AccountId });
        }

        [Authorize(Roles = WebConstants.OpportunityMemberRole)]
        public async Task<IActionResult> Edit(int id)
        {
            if (!await this.ValidateUserIsMemberOfOpportunityAsync(id))
            {
                return Unauthorized();
            }

            var serviceModel = await this.opportunities.GetByIdAsync(id);

            if (serviceModel == null)
            {
                return BadRequest();
            }

            var viewModel = Mapper.Map<OpportunityDetailsServiceModel, OpportunityFormModel>(serviceModel);

            viewModel.PotentialMembers = await this.GetUsersInOpportunityMemberRoleAsync();

            return this.ViewOrNotFound(viewModel);
        }

        [Authorize(Roles = WebConstants.OpportunityMemberRole)]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, OpportunityFormModel model)
        {
            if (!await this.ValidateUserIsMemberOfOpportunityAsync(id))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                model.PotentialMembers = await GetUsersInOpportunityMemberRoleAsync();
                return View(model);
            }

            var serviceModel = await this.opportunities.GetByIdAsync(id);

            if (serviceModel == null)
            {
                return BadRequest();
            }

            await this.opportunities.EditAsync(
                id,
                model.Name,
                model.Description,
                model.OportunityMembers);

            TempData.AddSuccessMessage($"Opportunity {model.Name} edited successfully!");
            return RedirectToAction(nameof(Details), routeValues: new { id = id });
        }

        private async Task<bool> ValidateUserIsMemberOfOpportunityAsync(int opportunityId)
        {
            var userId = this.userManager.GetUserId(User);

            var userIsMemberOfOpportunity = await this.opportunities.UserIsMemberOfOpportunity(userId, opportunityId);

            return userIsMemberOfOpportunity;
        }

        private async Task<IEnumerable<SelectListItem>> GetUsersInOpportunityMemberRoleAsync()
        {
            var opportunityMembers = await this.userManager.GetUsersInRoleAsync(WebConstants.OpportunityMemberRole);

            var opportunityMembersListItems = opportunityMembers
                .Select(t => new SelectListItem
                {
                    Text = t.UserName,
                    Value = t.Id
                });

            return opportunityMembersListItems;
        }

        private async Task<bool> ValidateUserIsAssignedAccountManager(int accountid)
        {
            var userId = this.userManager.GetUserId(User);
            var userIsAssignedAccountManager = await this.accounts.UserIsAssignedAccountManager(userId, accountid);

            return userIsAssignedAccountManager;
        }
    }
}

OfferMaker.Web/Views/Accounts/Create.cshtml
@model AddAccountFormModel

@{
    ViewData["Title"] = "Create account";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success">Create account</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

OfferMaker.Web/Views/Accounts/Delete.cshtml
@model AccountDetailsServiceModel

@{
    ViewData["Title"] = $"Delete {Model.Name} account";
}

<h2 class="text-danger">Are you sure you want to delete @Model.Name account?</h2>

<div class="panel panel-default">
    <div class="panel-heading"><strong>@Model.Name</strong></div>
    <div class="panel-body">
        <p>@Model.Description</p>
        <p><small>@Model.Address</small></p>
    </div>
</div>

<form method="post">
    <input type="hidden" asp-for="@Model.Id" />
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

OfferMaker.Web/Views/Accounts/Details.cshtml
@model AccountDetailsViewModel

@{
    ViewData["Title"] = $"{Model.Account.Name} details";
}

<h2></h2>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><strong>@Model.Account.Name</strong></div>
    <div class="panel-body">
        <p>@Model.Account.Description</p>
        <p><small>@Model.Account.Address</small></p>
        @if (User.IsInRole(WebConstants.AccountManagerRole) && Model.UserIsAssignedAccountManager)
        {
            <p id="manage-buttons">
                <a class="btn btn-primary" asp-controller="Opportunities" asp-action="Create" asp-route-accountId="@Model.Account.Id">Add Opportunity</a>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Account.Id">Edit</a>
                <a class="btn btn-primary" asp-action="Delete" asp-route-id="@Model.Account.Id">Delete</a>
            </p>
        }
    </div>

    @if (Model.Account.Opportunities != null && Model.Account.Opportunities.Count() >= 1)
    {
        <!-- Table -->
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Opportunity</th>
                    <th>Created on</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var opportunity in Model.Account.Opportunities)
                {
                    <tr>
                        <td><a asp-controller="Opportunities" asp-action="Details" asp-route-id="@opportunity.Id">@opportunity.Name</a></td>
                        <td>@opportunity.CreationDate</td>
                        <td>@opportunity.Id</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

OfferMaker.Web/Views/Accounts/Edit.cshtml
@model AccountFormModel

@{
    ViewData["Title"] = "Edit account";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-4">
        @Html.Partial("_AccountForm", Model)
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

OfferMaker.Web/Views/Accounts/Index.cshtml
@model IEnumerable<AccountListingServiceModel>

@{
    ViewData["Title"] = "Accounts";
}

<h2>@ViewData["Title"]</h2>

@if (User.IsInRole(WebConstants.AccountManagerRole))
{
    <p>
        <a class="btn btn-default" asp-controller="Accounts" asp-action="Create">Add new</a>
    </p>
}

<div class="row">
    @foreach (var account in Model)
    {
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading text-center">
                    <a asp-controller="Accounts" asp-action="Details" asp-route-id="@account.Id">@account.Name</a>
                </div>
                <div class="panel-body">
                    <p class="text-center">@account.Description</p>
                    @if (!String.IsNullOrEmpty(account.Address))
                    {
                        <p>Adrress: @account.Address</p>
                    }
                    <p>Account Manager: @account.ManagerName</p>
                    <p>@account.OpportunitiesCount Sales Opportunities</p>
                </div>
            </div>
        </div>
    }
</div>

OfferMaker.Web/Views/Accounts/_AccountForm.cshtml
@model AccountFormModel

<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success">Save Account</button>
</form>