OfferMaker.Web/Controllers/AccountsController.cs
namespace OfferMaker.Web.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using OfferMaker.Data.Models;
    using OfferMaker.Services;
    using OfferMaker.Services.Models.Account;
    using OfferMaker.Web.Infrastructure.Extensions;
    using OfferMaker.Web.Models.Account;
    using System.Threading.Tasks;


    public class AccountsController : Controller
    {
        private readonly IAccountService accounts;
        private readonly UserManager<User> userManager;

        public AccountsController(IAccountService accounts, UserManager<User> userManager)
        {
            this.accounts = accounts;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            return View(await this.accounts.GetAllAsync());
        }

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        public IActionResult Create()
            => View(new AccountFormModel());

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        [HttpPost]
        public async Task<IActionResult> Create(AccountFormModel accountModel)
        {
            if (!ModelState.IsValid)
            {
                return View(accountModel);
            }

            var userId = this.userManager.GetUserId(User);

            await this.accounts.CreateAsync(
                accountModel.Name,
                accountModel.Address,
                accountModel.Description,
                userId);

            TempData.AddSuccessMessage($"Account {accountModel.Name} created successfully!");
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var account = await this.accounts.GetByIdAsync(id);

            if (account == null)
            {
                return NotFound();
            }

            var userId = this.userManager.GetUserId(User);
            var userIsAssignedAccountManager = await this.accounts.UserIsAssignedAccountManager(userId, id);

            var accountViewModel = new AccountDetailsViewModel
            {
                Account = account,
                UserIsAssignedAccountManager = userIsAssignedAccountManager
            };

            return View(accountViewModel);
        }

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        public async Task<IActionResult> Delete(int id)
        {
            if (!await this.ValidateUserIsAssignedAccountManager(id))
            {
                return Unauthorized();
            }

            var model = await this.accounts.GetByIdAsync(id);
            return this.ViewOrNotFound(model);
        }

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!await this.ValidateUserIsAssignedAccountManager(id))
            {
                return Unauthorized();
            }

            var model = await this.accounts.GetByIdAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            var result = await this.accounts.DeleteAsync(id);
            if (!result)
            {
                return NotFound();
            }

            TempData.AddSuccessMessage($"Account {model.Name} deleted successfully!");
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        public async Task<IActionResult> Edit(int id)
        {
            if (!await this.ValidateUserIsAssignedAccountManager(id))
            {
                return Unauthorized();
            }

            var serviceModel = await this.accounts.GetByIdAsync(id);

            var viewModel = Mapper.Map<AccountDetailsServiceModel, AccountFormModel>(serviceModel);

            return this.ViewOrNotFound(viewModel);
        }

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, AccountFormModel model)
        {
            if (!await this.ValidateUserIsAssignedAccountManager(id))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var serviceModel = await this.accounts.GetByIdAsync(id);

            if (serviceModel == null)
            {
                return BadRequest();
            }

            await this.accounts.EditAsync(id, model.Name, model.Description, model.Address);

            TempData.AddSuccessMessage($"Account {model.Name} edited successfully!");
            return RedirectToAction(nameof(Details), routeValues: new { id = id });
        }

        private async Task<bool> ValidateUserIsAssignedAccountManager(int accountid)
        {
            var userId = this.userManager.GetUserId(User);
            var userIsAssignedAccountManager = await this.accounts.UserIsAssignedAccountManager(userId, accountid);

            return userIsAssignedAccountManager;
        }
    }
}

OfferMaker.Web/Controllers/ProposalsController.cs
namespace OfferMaker.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Identity;
    using OfferMaker.Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using OfferMaker.Services;
    using OfferMaker.Web.Models.Proposal;
    using OfferMaker.Web.Infrastructure.Extensions;
    using System.IO;
    using OfferMaker.Data;

    public class ProposalsController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IProposalService proposals;
        private readonly IOpportunityService opportunities;
        private readonly IAccountService accounts;

        public ProposalsController(UserManager<User> userManager, IProposalService proposals, IOpportunityService opportunities, IAccountService accounts)
        {
            this.userManager = userManager;
            this.proposals = proposals;
            this.opportunities = opportunities;
            this.accounts = accounts;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userId = this.userManager.GetUserId(User);

            if (User.IsInRole(WebConstants.AccountManagerRole))
            {
                return View(await this.proposals.GetAllByManagerAsync(userId));
            }

            return View(await this.proposals.GetAllByUserAsync(userId));
        }

        [Authorize(Roles = WebConstants.OpportunityMemberRole)]
        public async Task<IActionResult> Create(int opportunityId)
        {
            if (!await this.ValidateUserIsMemberOfOpportunityAsync(opportunityId))
            {
                return Unauthorized();
            }

            var model = new ProposalFormModel
            {
                OpportunityId = opportunityId
            };

            return View(model);
        }

        [Authorize(Roles = WebConstants.OpportunityMemberRole)]
        [HttpPost]
        public async Task<IActionResult> Create(ProposalFormModel model)
        {
            if (!await this.ValidateUserIsMemberOfOpportunityAsync(model.OpportunityId))
            {
                return Unauthorized();
            }

            if (model.File != null && (!model.File.FileName.EndsWith(".pdf") || model.File.Length > DataConstants.UploadFileLenght))
            {
                ModelState.AddModelError("File", "File should be .pdf, no larger than 5 MB in size!");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.proposals.CreateAsync(
                model.Name,
                model.Value,
                model.Margin,
                model.OpportunityId,
                model.File);

            TempData.AddSuccessMessage($"Proposal {model.Name} created successfully!");
            return RedirectToAction(controllerName: "Opportunities", actionName: nameof(OpportunitiesController.Details), routeValues: new { id = model.OpportunityId });
        }

        [Authorize]
        public async Task<IActionResult> DownloadFile(int proposalId)
        {
            var proposal = await this.proposals.GetByIdAsync(proposalId);
            if (proposal == null)
            {
                return BadRequest();
            }

            var userId = this.userManager.GetUserId(User);
            if (await this.ValidateUserIsMemberOfOpportunityAsync(proposal.OpportunityId) || await this.accounts.UserIsAssignedAccountManager(userId, proposal.AccountId))
            {
                var file = await this.proposals.GetFileAsync(proposalId);
                if (file == null)
                {
                    return BadRequest();
                }
                return File(file, "application/pdf", $"{proposal.Name} summary.pdf");
            }

            else
            {
                return Unauthorized();
            }
        }

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        [HttpPost]
        public async Task<IActionResult> Approve(int proposalId)
        {
            var proposal = await this.proposals.GetByIdAsync(proposalId);
            if (proposal == null)
            {
                return BadRequest();
            }

            var userId = this.userManager.GetUserId(User);
            if (!await this.accounts.UserIsAssignedAccountManager(userId, proposal.AccountId))
            {
                Unauthorized();
            }

            var result = await this.proposals.ApproveAsync(proposalId);
            if (!result)
            {
                return NotFound();
            }

            TempData.AddSuccessMessage($"Proposal {proposal.Name} was approved successfully!");
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = WebConstants.AccountManagerRole)]
        [HttpPost]
        public async Task<IActionResult> Reject(int proposalId)
        {
            var proposal = await this.proposals.GetByIdAsync(proposalId);
            if (proposal == null)
            {
                return BadRequest();
            }

            var userId = this.userManager.GetUserId(User);
            if (!await this.accounts.UserIsAssignedAccountManager(userId, proposal.AccountId))
            {
                Unauthorized();
            }

            var result = await this.proposals.RejectAsync(proposalId);
            if (!result)
            {
                return NotFound();
            }

            TempData.AddSuccessMessage($"Proposal {proposal.Name} was rejected successfully!");
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> ValidateUserIsMemberOfOpportunityAsync(int opportunityId)
        {
            var userId = this.userManager.GetUserId(User);

            var userIsMemberOfOpportunity = await this.opportunities.UserIsMemberOfOpportunity(userId, opportunityId);

            return userIsMemberOfOpportunity;
        }
    }
}

OfferMaker.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Offer Maker</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Accounts" asp-action="Index" class="navbar-brand">Offer Maker</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole(WebConstants.AdministratorRole))
                    {
                        <li><a asp-area="@WebConstants.AdminArea" asp-controller="Users" asp-action="Index">Users</a></li>
                    }
                    <li><a asp-area="" asp-controller="Accounts" asp-action="Index">Accounts</a></li>
                    <li><a asp-area="" asp-controller="Opportunities" asp-action="Index">Opportunities</a></li>
                    <li><a asp-area="" asp-controller="Proposals" asp-action="Index">Proposals</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (TempData.ContainsKey(WebConstants.TempDataSuccessMessageKey))
        {
            <div class="alert alert-success">
                @TempData[WebConstants.TempDataSuccessMessageKey]
            </div>
        }

        @RenderBody()

        <hr />
        <footer>
            <p>&copy; 2017 - Offer Maker</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>